import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {GeistSans} from "geist/font/sans";
import {GeistMono} from "geist/font/mono";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from 'next-themes'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(GeistMono.variable,GeistSans.variable, "h-full")}>
        <Toaster/>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
